all:
	gcc -o example example.c -LC:/Windows -lcrossdb -lpthread
	./example

#debug:
#	gcc -o example example.c -LC:/Windows ../../src/crossdb.c -lpthread -g -fsanitize=address
#	./example
#
#gdb:
#	gcc -o example example.c -LC:/Windows ../../src/crossdb.c -lpthread -g -fsanitize=address
#	gdb example
#
#clean:
#	rm -f a.out example