/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_open_crossdb_jni_core_CrossDBJNI */

#ifndef _Included_com_open_crossdb_jni_core_CrossDBJNI
#define _Included_com_open_crossdb_jni_core_CrossDBJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniOpenDB
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniOpenDB
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniBegin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniBegin
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniCommit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniCommit
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniRollback
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniRollback
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniXdbExec
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniXdbExec
        (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniFetchRow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniFetchRow
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniColumnInt
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniColumnInt
        (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniColumnStr
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniColumnStr
        (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniColumnFloat
 * Signature: (JJI)F
 */
JNIEXPORT jfloat JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniColumnFloat
        (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_open_crossdb_jni_core_CrossDBJNI
 * Method:    jniClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_open_crossdb_jni_core_CrossDBJNI_jniClose
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
